version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: rclone-sync-mongodb_container
    environment:
      MONGO_INITDB_DATABASE: rclone
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - rclone-sync-net
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: rclone-sync-redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./logs:/var/log/supervisor
    networks:
      - rclone-sync-net
    restart: unless-stopped

  backend:
    image: zane626/rclone-sync-hub-backend:latest
    container_name: rclone-sync-hub-backend_container
    env_file:
      - ./.env.prod
    environment:
      - FLASK_ENV=production
    ports:
      - "5001:5001"
      - "5555:5555"  # Flower监控界面
    depends_on:
      - mongodb
      - redis
    networks:
      - rclone-sync-net
    restart: unless-stopped
    volumes:
      - .:/volume
      - ./config:/root/.config/rclone

  frontend:
    image: zane626/rclone-sync-hub-frontend:latest
    container_name: rclone-sync-hub-frontend_container
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:5001  # 指向app服务
    depends_on:
      - backend
    networks:
      - rclone-sync-net

networks:
  rclone-sync-net:
    driver: bridge
