version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: rclone-sync-mongodb_container
    environment:
      MONGO_INITDB_DATABASE: rclone
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - rclone-sync-net
    restart: unless-stopped

  backend:
    image: zane626/rclone-sync-hub-backend:latest
    container_name: rclone-sync-hub-backend_container
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/rclone
    ports:
      - "5052:5001"
    depends_on:
      - mongodb
    networks:
      - rclone-sync-netz
    restart: unless-stopped
    volumes:
      - .:/volume # 挂载需要检测的资源文件夹
      - ./config:/root/.config/rclone # 挂载rclone配置文件夹

  frontend:
    image: zane626/rclone-sync-hub-frontend:latest
    container_name: rclone-sync-hub-frontend_container
    ports:
      - "5051:80"
    environment:
      - API_URL=http://backend:5002  # 指向app服务
    depends_on:
      - backend
    networks:
      - rclone-sync-net

networks:
  rclone-sync-net:
    driver: bridge
